# Default values for ifitfitsicommits.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values for proglog.
image:
  repository: github.com/idclark/ifitfitsicommits
  tag: 0.0.1
  pullPolicy: IfNotPresent
serfPort: 8401
rpcPort: 8400
replicas: 3
storage: 1Gi
